# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
all:
  vars:
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: riku
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWIF63S4f3z9wQMvWibmvl7MPuJ6EVrkP0HuvgNhcs/4DZYMcR/GRBvV4ldOSYMlBevIXycgGzNDxKJgENUuwIWanjBu7uVAHyD6+cIRD1h63qq7Cjv/2HYTfBDKOrKzPOhA6zWvKO0ZGWsjRXk5LWMCbKOkvKJCxOpj/NVBxeE4FTK5YADYPV3OSsmBtqTHrVLm2sMmShU/2hMYYswWkobidjX65+nK/X+3C+yJbHwiydVvn+QCrFlFfCLPWKe8rUpOxyxofPqWVQh6CHhHfT8okaOc9sOE8Qeip9ljo84DftJh3Xm3ynOdWK1hH2BvRvxNadWqcE1qECbkg4tx2x riku.rouvila@gmail.com
        state: present
        sudoer: true
      - name: euan
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDECqHO65UpyrrO8uueD06RxGaVVq22f152Rf8qVQQAAIGAMu6gCs7ztlZ8a3yQgSEIjM/Jl1/RqIVs6CziTEef74nLFTZ5Ufz3CLRVgdebBeSBEmhTfTUV0HLkSyNzwKFpuzJxucGd72ulPvEp6eHvyJAPJz37YcU8cjaL1v05T6s2ee99li35GlDDtCzfjVV4ZPAg5JdfWuTj41RAVC0LQhk2/NB4qEu37UxGGjhRFSjBEsS5LxI9QfvgrsHpl/VOn+soH7ZkK7kS6qRgNP/uYsXRWXhHaamcl5OX68gJWTbrW6c7PCqlbCWGnsHJswCmqPIthwXXMfC7ULDNLSKG6mslAt5Dyc8/MCr3vTW7pDyr2d0FvvY86SMQUggxv3qF7TZewqfX1bhK0fMLarIxVMQ1RFo//wN9QGA+2we8rxd2Y1Kr1DBuJyuwXPfv+Exo8yNYQ+x/AYH5k6UVcSYuaB8eYmplG2KQCxt8RBFtoChrwOKNRWLqXdKyfpdp5XmnnWxPvR95gf3h3yLocVYkF0i0uvKKJ0vt8J0Ezfkdfow0B1kUg5bPXKJROX7PwbaCPdYcxyDaO6wwOigRnSmoFvkH1pLb4j1RQAXcX531CHgfN6Izi/h0mpMS4bnyIUcv2GQr+h4z4TxcCtj7qpH2y6yw7XG12jVh7TfeesXG2Q== euanmillar77@gmail.com
        state: present
        sudoer: true
      - name: ronald
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCCN3xjW33fLsAK5+wMZLGEEj8HraA/ZUWW5G7K3uvi+RuAQzhD2Loz9ulhXBT+hqpK2w8f+/ZcwknbVb4Zhd2GttKV0Fb3Yw0/sTVJaL9jGqL4GYK9ugvivqfa5OGh8Mo5HIa+Hi+v1vp1fiyV3Yzp5bSlyrL0zJjVdAU+Ss/L0ZqdLQ3+KmzFctCEe8L3SgOJ3Vh7T60X5V6ugSj8JVNC8tqxDJ53cFCRQP72w46I8ILhv1L+6VZnMVlaAFnwgo2xkWDSLbXQ4sJRFs9lDRdoUzmlfXwjgPpXdBcNVlqzipXwTU6KRJ7PI+N8Kw/ZITXHXA5vfzBwOgh+g7hNC3T MAC@MacBook-Pro
        state: present
        sudoer: true
      - name: septime
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCQYzf/TjdF8CaQGkviO3DLL8fRKKrYkxB+XGeC6FZvOEgG88mOak9l9sF7m7Wt2AKTIVJqRAieQO2vTokB45EZ3Pyuy5P6424v62IyZocbMknHQB4oloo2Xm1kIEjDlMu+s/S2EmZXu0uthTlqjME3Tgl7RzepjVmkJM5RKEn7wQ63huF32xsbSXdbcvj1PbhdYgkNBwwiwSKLwRiCs35dVpNqGJ6y4sggDC7iowte+DHtB2WwKpeDx5Pud4gAlVewcd7WpYtnfOA+B6PCBr3arNv1knVzraZpPo1x2Ro0fAeZwXcLq8MAWOpYLRjSyldovA3pLXsPCmw38UN5aOrH rsa-key-20240517
        state: present
        sudoer: true

      # @todo will this host be used as a bastion / jump server for the CI/CD pipeline to access production servers?
      # if no, then you can remove this user.
      - name: jump
        state: present
        sudoer: false
        two_factor: false
        ssh_keys:
          # if yes, then this should list the public keys of the private keys that are used when connecting to the production servers.
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO6SAQLbIKo17Mo13FL9j6/L8pco3i7dfqtESMel6Zs1 provision@prod # example provision user key
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBI0NjEoorVmb6NtedSdRWM7phbwsCdVfimHU3lqj/lK provision@staging # example provision user key

docker-manager-first:
  hosts:
    qa: # @todo set this to be the hostname of your target server
      ansible_host: '167.99.248.69' # @todo set this to be the IP address of your server
      data_label: data1 # for manager machines, this should always be "data1"

# QA and staging servers are not configured to use workers.
docker-workers: {}
