# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Example IP addressses used in this file:
# 11.11.11.11 - Target staging server's IP address
# 55.55.55.55 - This IP address is both the VPN server the server used as a bastion / jump host
# 66.66.66.66 - This IP address is the address of a backup server

all:
  vars:
    # This configuration variable blocks all access to the server, including SSH, except from the IP addresses specified below.
    # This should always be set when configuring a production server if there is no other firewall in front of the server.
    # SSH and other services should never be exposed to the public internet.
    only_allow_access_from_addresses:
      # @todo place the IP address of your VPN server or other explicitly allowed traffic sources here
      - 164.90.179.92 # example VPN server IP address
    enable_backups: false
    periodic_restore_from_backup: true
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: riku
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWIF63S4f3z9wQMvWibmvl7MPuJ6EVrkP0HuvgNhcs/4DZYMcR/GRBvV4ldOSYMlBevIXycgGzNDxKJgENUuwIWanjBu7uVAHyD6+cIRD1h63qq7Cjv/2HYTfBDKOrKzPOhA6zWvKO0ZGWsjRXk5LWMCbKOkvKJCxOpj/NVBxeE4FTK5YADYPV3OSsmBtqTHrVLm2sMmShU/2hMYYswWkobidjX65+nK/X+3C+yJbHwiydVvn+QCrFlFfCLPWKe8rUpOxyxofPqWVQh6CHhHfT8okaOc9sOE8Qeip9ljo84DftJh3Xm3ynOdWK1hH2BvRvxNadWqcE1qECbkg4tx2x riku.rouvila@gmail.com
        state: present
        sudoer: true
      - name: euan
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDECqHO65UpyrrO8uueD06RxGaVVq22f152Rf8qVQQAAIGAMu6gCs7ztlZ8a3yQgSEIjM/Jl1/RqIVs6CziTEef74nLFTZ5Ufz3CLRVgdebBeSBEmhTfTUV0HLkSyNzwKFpuzJxucGd72ulPvEp6eHvyJAPJz37YcU8cjaL1v05T6s2ee99li35GlDDtCzfjVV4ZPAg5JdfWuTj41RAVC0LQhk2/NB4qEu37UxGGjhRFSjBEsS5LxI9QfvgrsHpl/VOn+soH7ZkK7kS6qRgNP/uYsXRWXhHaamcl5OX68gJWTbrW6c7PCqlbCWGnsHJswCmqPIthwXXMfC7ULDNLSKG6mslAt5Dyc8/MCr3vTW7pDyr2d0FvvY86SMQUggxv3qF7TZewqfX1bhK0fMLarIxVMQ1RFo//wN9QGA+2we8rxd2Y1Kr1DBuJyuwXPfv+Exo8yNYQ+x/AYH5k6UVcSYuaB8eYmplG2KQCxt8RBFtoChrwOKNRWLqXdKyfpdp5XmnnWxPvR95gf3h3yLocVYkF0i0uvKKJ0vt8J0Ezfkdfow0B1kUg5bPXKJROX7PwbaCPdYcxyDaO6wwOigRnSmoFvkH1pLb4j1RQAXcX531CHgfN6Izi/h0mpMS4bnyIUcv2GQr+h4z4TxcCtj7qpH2y6yw7XG12jVh7TfeesXG2Q== euanmillar77@gmail.com
        state: present
        sudoer: true
      - name: ronald
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCCN3xjW33fLsAK5+wMZLGEEj8HraA/ZUWW5G7K3uvi+RuAQzhD2Loz9ulhXBT+hqpK2w8f+/ZcwknbVb4Zhd2GttKV0Fb3Yw0/sTVJaL9jGqL4GYK9ugvivqfa5OGh8Mo5HIa+Hi+v1vp1fiyV3Yzp5bSlyrL0zJjVdAU+Ss/L0ZqdLQ3+KmzFctCEe8L3SgOJ3Vh7T60X5V6ugSj8JVNC8tqxDJ53cFCRQP72w46I8ILhv1L+6VZnMVlaAFnwgo2xkWDSLbXQ4sJRFs9lDRdoUzmlfXwjgPpXdBcNVlqzipXwTU6KRJ7PI+N8Kw/ZITXHXA5vfzBwOgh+g7hNC3T MAC@MacBook-Pro
        state: present
        sudoer: true
      - name: septimelowe
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/nO+cHvwgTFuqLomSB/qoFZhdxOFDGLnDvBXak8J8VaJzYozGfQKdkP6jf3MeIE2iw7vwx1yn6prwGWBVk9Es4ElvAuoYnD8tJg1SPYiUtDFKRK25SUw9178GuAyf5wgw4GBHt/81n6h8NlgqJ7OXncFfGMOFVxKZftxB3AAKg2rvbO6UEghVt/UeWFcU6Ar4V40pvYXMZ+W3opoQLOrzpFSG537goWdUu6KSK+HIKoqCUP1yPPF2JYoqZDuuh1fKCWNtB/BnRiEEIuCj2INinjhoIK79oeMtFqgdmGB1M9md3FNDnu86h6njcOY0VkuL1LfjjbkelUpF0kIZnaSn6En3s7armZDQ2mi0DvMgvIDBlKQA0XK3kkNgmujRragNH7Nrer1AM5RMAvadnV9JgOWnvOFZOWCxdGYFHv+OW4fC7ofbNbVc+vI+BQ+SmHTUlSzjDaRF0Jaw3cOe+Wt+ckcDZ5ltdzJvx+QiSz7tBS0AyAY67rAErJkPxqbJTxnCnLKe8soy+Qdm1ppy4g4j/ORPScBnXSXt0jdQ89nTrz2kMOhYgdTE/kMFZcuwa9URDJq5OfCmoU2mCY2zvB7jYXVziheSlAuF7thqpzdsUWsMqRiZswlf+x8hTQ68A764Re3yxBmw1pV0+iq0b5Q7BQw3Uc6cPjdpdv666DWbGQ== septime.lowe@gmail.com
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    staging: # @todo set this to be the hostname of your target server
      ansible_host: '165.232.119.159' # todo set this to be the hostname of your target server
      data_label: data1
      # @todo as production servers are not directly accessible from the internet, you need to use a jump server to access them.
      ansible_ssh_common_args: '-J jump@164.90.179.92 -o StrictHostKeyChecking=no'

# This staging servers is configured to only use one server
docker-workers: {}

# For staging server to be able to restore from backups, it needs to have access to the backup server.
# @todo if you do not intend to set up automatic sync from the backup server, you can remove this section.
backups:
  hosts:
    backup: # @todo set this to be the hostname of your backup server
      ansible_host: '46.101.99.140' # set this to be the IP address of your backup server
